// One shared fallback for the public pricing page and the authenticated editor.
(function faqData(){
  'use strict';
  if(Array.isArray(window.ABATCHAN_FAQ_DEFAULTS))return;
  window.ABATCHAN_FAQ_DEFAULTS=[
    {id:'pricing-starting-points',page:'/pricing',question:'Why are the prices shown as starting points?',answer:'Two projects can look similar but have very different content, integrations, account systems, technical debt, or deadline pressure. The starting price gives you the correct budget range before the detailed scope is prepared.',published:true},
    {id:'pricing-payments',page:'/pricing',question:'How do payments work?',answer:'Payments are handled by invoice, not a generic checkout button. Medium and large projects are split into milestones tied to clear deliverables, and each invoice lists the available payment method.',published:true},
    {id:'pricing-phases',page:'/pricing',question:'Can I start smaller and add more later?',answer:'Yes, provided the first version is designed with the later phases in mind. The scope can be arranged as a focused first release followed by measured improvements.',published:true},
    {id:'pricing-existing-work',page:'/pricing',question:'Do you work with existing websites and products?',answer:'Yes. Existing work is reviewed first because poor structure, outdated plugins, missing documentation, or unstable integrations can affect the quote.',published:true},
    {id:'pricing-timeline',page:'/pricing',question:'How quickly can a website be delivered?',answer:'A focused landing page is commonly completed in 2–3 working days, while a focused five-page business website can often be completed in about 5 working days when content, access, references, and feedback are ready. Ecommerce, dashboards, migrations, custom functionality, and integrations take longer.',published:true},
    {id:'pricing-existing-systems',page:'/pricing',question:'Can you work on an existing website or system?',answer:'Yes. Existing WordPress, Shopify, Wix, Framer, BookingKoala, directory, membership, and automation setups can be reviewed, repaired, extended, migrated, or redesigned. The current structure is checked first because technical debt, unstable plugins, and missing documentation can affect the scope.',published:true},
    {id:'pricing-integrations',page:'/pricing',question:'Can you connect forms, payments, booking tools, and other platforms?',answer:'Yes. Past work includes Stripe, HubSpot, Google Maps and Places, BookingKoala, Calendly, Tally, GoHighLevel, Zapier, OpenPhone, analytics, ecommerce, and custom API integrations. Access requirements and each system’s limitations are confirmed during scope.',published:true},
    {id:'pricing-custom-work',page:'/pricing',question:'Do you build custom features or only use templates?',answer:'Both. Templates and established components are used when they save time without limiting the result. Custom code is used for unique workflows, plugins, dashboards, account logic, APIs, forms, product structures, and frontend behavior that off-the-shelf tools cannot handle cleanly.',published:true},
    {id:'pricing-revisions',page:'/pricing',question:'How are revisions and changing requirements handled?',answer:'The agreed scope is divided into milestones with clear deliverables. Normal feedback within that scope is handled during the relevant milestone. New pages, integrations, workflows, or requirements are estimated separately before work continues.',published:true},
    {id:'pricing-requirements',page:'/pricing',question:'What do you need from me before work starts?',answer:'Usually the content, brand assets, references, required access, integrations, deadline, and the outcome the project must achieve. Fast timelines depend on those items being available and feedback arriving without long delays.',published:true},
    {id:'pricing-branding',page:'/pricing',question:'Do you provide branding as part of a website project?',answer:'Branding can be added, but it is a separate premium service. Logo systems, identity direction, typography, colours, brand guidelines, social assets, and launch materials require their own creative scope rather than being treated as a free website extra.',published:true},
    {id:'pricing-after-launch',page:'/pricing',question:'What happens after launch?',answer:'Projects include testing, deployment, and an agreed handover. Ongoing maintenance, improvements, product updates, analytics, technical support, and automation monitoring can continue under hourly work or a monthly support arrangement.',published:true}
  ];
})();
