const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const intro=q('.intro');
if(intro){const video=q('video',intro),skip=q('.skip',intro);const close=()=>{intro.classList.add('hidden');sessionStorage.setItem('abatIntro','1');setTimeout(()=>intro.remove(),800)};if(sessionStorage.getItem('abatIntro'))close();else{video?.play().catch(()=>{});video?.addEventListener('ended',close);skip?.addEventListener('click',close);setTimeout(close,6500)}}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});qa('.reveal').forEach(e=>observer.observe(e));
document.addEventListener('mousemove',e=>{const light=q('.cursor-light');if(light){light.style.left=e.clientX+'px';light.style.top=e.clientY+'px'}});
const stage=q('.system-stage'),core=q('.system-core');if(stage&&core){stage.addEventListener('mousemove',e=>{const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;core.style.transform=`rotateY(${x*12}deg) rotateX(${-y*10}deg)`});stage.addEventListener('mouseleave',()=>core.style.transform='')}
const internal=h=>!!h&&h.startsWith('/')&&!h.startsWith('//');
qa('a[href]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.button!==0||a.target==='_blank')return;const href=a.getAttribute('href');if(!internal(href))return;e.preventDefault();q('.page-transition')?.classList.add('go');setTimeout(()=>location.href=href,390)}));
const path=location.pathname.replace(/\.html$/,'').replace(/\/index$/,'/').replace(/(.)\/$/,'$1')||'/';qa('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===path));
qa('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{qa('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;qa('.work-card').forEach(card=>card.style.display=(f==='all'||card.dataset.type===f)?'flex':'none')}));
const form=q('#project-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const subject=encodeURIComponent(`Project enquiry — ${d.get('name')}`);const body=encodeURIComponent(`Name: ${d.get('name')}\nEmail: ${d.get('email')}\nProject type: ${d.get('type')}\n\n${d.get('message')}`);location.href=`mailto:hello@abatchan.com?subject=${subject}&body=${body}`});