import { readFileSync } from 'node:fs';

const php=readFileSync(new URL('../wordpress/nika-site-guide/nika-site-guide.php',import.meta.url),'utf8');
const readme=readFileSync(new URL('../wordpress/nika-site-guide/readme.txt',import.meta.url),'utf8');
const widget=readFileSync(new URL('../wordpress/nika-site-guide/assets/nika-widget.js',import.meta.url),'utf8');
const adminCss=readFileSync(new URL('../wordpress/nika-site-guide/assets/nika-admin.css',import.meta.url),'utf8');
const adminJs=readFileSync(new URL('../wordpress/nika-site-guide/assets/nika-admin.js',import.meta.url),'utf8');
const adminIcon=readFileSync(new URL('../wordpress/nika-site-guide/assets/nika-admin-icon.png',import.meta.url));
const canonicalAdminIcon=readFileSync(new URL('../assets/abatchan-symbol-white-tight-504x308.png',import.meta.url));
const updateManifest=JSON.parse(readFileSync(new URL('../downloads/nika-site-guide-update.json',import.meta.url),'utf8'));
const canonical=readFileSync(new URL('../products/nika-core/nika-widget.js',import.meta.url),'utf8');
const adminPage=php.slice(php.indexOf('function nika_settings_page()'),php.indexOf('function nika_excluded_paths()'));

let failed=false;
const check=(label,value)=>{const pass=Boolean(value);console.log(`${pass?'PASS':'FAIL'}  ${label}`);if(!pass)failed=true;};

console.log('=== self-hosted WordPress adapter ===');
check('plugin is GPL licensed',php.includes('License:           GPL-2.0-or-later'));
check('supports BYOK providers',php.includes("'openai', 'deepseek', 'compatible'"));
check('uses a dedicated top-level WordPress admin menu',php.includes("add_menu_page(")&&!php.includes('add_options_page(')&&php.includes("'toplevel_page_nika-site-guide'"));
check('ships the canonical transparent white Abatchan admin icon',adminIcon.equals(canonicalAdminIcon));
check('ships a responsive branded settings workspace',adminCss.includes('.nika-hero')&&adminCss.includes('.nika-shell')&&adminCss.includes('@media (max-width: 782px)'));
check('offers automatic future WordPress update notices',php.includes('pre_set_site_transient_update_plugins')&&php.includes('NIKA_UPDATE_MANIFEST')&&php.includes("'plugins_api'"));
check('update downloads are restricted to the trusted HTTPS host',php.includes("'https' !== ( $parts['scheme']")&&php.includes("'abatchan.com' !== strtolower"));
check('published update manifest matches the plugin version',updateManifest.version==='0.5.2'&&updateManifest.package.endsWith('/nika-site-guide-0.5.2.zip')&&php.includes("const NIKA_VERSION = '0.5.2'"));
check('a forced WordPress update check refetches the release manifest',php.includes("add_action( 'load-update-core.php'")&&php.includes("nika_forget_update_manifest")&&php.includes("delete_site_transient( 'nika_update_manifest_v1' )")&&php.includes("upgrader_process_complete"));
check('model is a select that can be filled from the provider model list',php.includes("'/admin/models'")&&php.includes('nika_models_response')&&php.includes('nika_provider_models_url')&&php.includes('<select class="code" id="nika-model"')&&adminJs.includes('modelsEndpoint')&&adminJs.includes('fillModels'));
check('a custom model can still be typed for compatible providers',php.includes('id="nika-model-custom"')&&php.includes('__custom__')&&adminJs.includes('syncCustomMode')&&adminJs.includes("modelCustom.setAttribute('name', fieldName)"));
check('the model list request requires an HTTPS compatible endpoint',php.includes("'https' !== ( $parts['scheme'] ?? '' ) || empty( $parts['host'] )"));
check('generated suggestions are typed in and respect reduced motion',adminJs.includes('typeInto')&&adminJs.includes('prefers-reduced-motion')&&adminJs.includes("classList.add('is-typing')")&&adminCss.includes('input.is-typing'));
check('the generator button is compact and carries an icon',php.includes('nika-generate__icon')&&adminCss.includes('.nika-generate__icon')&&adminCss.includes('min-height: 30px')&&adminCss.includes('font-size: 12px'));
check('provider errors are spaced away from the suggestion form',adminCss.includes('.nika-admin .nika-generator-status { display: none; margin: 26px 0 0;')&&adminCss.includes('align-self: flex-start'));
check('the model list is cached and the reload control forces a refresh',php.includes('nika_models_cache_key')&&php.includes('set_transient( nika_models_cache_key( $s ), $models, 12 * HOUR_IN_SECONDS )')&&php.includes('nika_cached_models( $s )')&&adminJs.includes('?refresh=1'));
check('changing provider, endpoint or key drops the cached model list',php.includes('nika_forget_models_cache')&&php.includes("$provider !== $old['provider'] || $endpoint !== $old['endpoint'] || $key !== $old['api_key']"));
check('the reload control explains itself and warns about unsaved provider changes',php.includes('data-tip=')&&adminCss.includes('.nika-tip::after')&&adminJs.includes('providerDirty')&&adminJs.includes('Save your provider changes first.'));
check('unsaved changes are reflected on the save bar',adminJs.includes('is-dirty')&&adminJs.includes('You have unsaved changes.')&&adminCss.includes('.nika-savebar.is-dirty'));
check('a blocked clipboard degrades to a selected key rather than a raw browser error',adminJs.includes('offerManualCopy')&&adminJs.includes('setSelectionRange')&&adminJs.includes('copy it with Ctrl or Cmd and C'));
check('the saved key is masked, revealable and copyable by an administrator',php.includes("'/admin/key'")&&php.includes('nika_reveal_key_response')&&php.includes('id="nika-key-reveal"')&&php.includes('id="nika-key-copy"')&&adminJs.includes('navigator.clipboard.writeText'));
check('a wp-config key is never posted back into the database',php.includes("'source' => 'wp-config'")&&adminJs.includes("data.source === 'wp-config'")&&adminJs.includes("keyInput.removeAttribute('name')"));
check('the key is still never exposed to visitors',!php.match(/nika_config_response[\s\S]{0,800}api_key/)&&php.includes("register_rest_route( 'nika/v1', '/admin/key'")&&php.match(/'\/admin\/key'[\s\S]{0,220}manage_options/));
check('a hidden conditional field is really hidden, not just flagged',adminCss.includes('.nika-admin [hidden] { display: none !important; }'));
check('switching provider resets the model to that provider default',php.includes("'defaultModels' => array(")&&adminJs.includes('defaultModels')&&adminJs.includes('Model reset to'));
check('fields that depend on another choice are hidden until it is made',php.includes('data-nika-when="provider" data-nika-equals="compatible"')&&php.includes('data-nika-when="dictation"')&&adminJs.includes('syncConditionals'));
check('suggestion parsing accepts the shapes models actually return',php.includes('nika_extract_suggestions')&&php.includes('nika_json_slice')&&php.includes("'suggestions', 'items', 'questions', 'starters', 'data', 'results'")&&php.includes("'label', 'title', 'question', 'name', 'heading'"));
check('the retry differs from the first attempt instead of repeating it',php.includes('Example for an unrelated bicycle repair shop')&&php.includes("'compatible' !== $s['provider'] && ! $strict"));
check('a short suggestion reply is retried once before failing',php.includes('nika_request_suggestions( $s, $provider, $key, $content, true )')&&php.includes("'max_tokens' => 900"));
check('an incomplete generation says how many came back and from which model',php.includes('returned %2$d usable suggestions instead of three')&&php.includes("\$provider['model']"));
check('form controls share one height instead of selects standing taller',adminCss.includes('line-height: 1.4;')&&adminCss.includes('WordPress gives admin selects a 38px line-height'));
check('placeholder echoes are never accepted as suggestions',php.includes('nika_is_placeholder_text')&&php.includes('Never return placeholder text, ellipses')&&!php.includes('{\"label\":\"...\"'));
check('suggestion fields fill together instead of one after another',adminJs.includes('const TYPE_MS = 420')&&adminJs.includes('requestAnimationFrame')&&!adminJs.includes('index * 130'));
check('generating and saving both show they are working',adminJs.includes("submit.value = 'Saving...'")&&adminJs.includes('Saving your changes.')&&adminCss.includes('.nika-generate[aria-busy="true"] .nika-generate__icon')&&adminCss.includes('nika-sweep'));
check('website instructions can be drafted from published content',php.includes("'/admin/instructions'")&&php.includes('nika_generate_instructions_response')&&php.includes('id="nika-generate-instructions"')&&adminJs.includes('instructionsEndpoint'));
check('replacing written instructions asks twice without a blocking dialog',adminJs.includes('Click Draft again to continue.')&&!adminJs.includes('window.confirm'));
check('the widget stylesheet is versioned so upgrades are not served from cache',php.includes("add_query_arg( 'ver', NIKA_VERSION, plugin_dir_url( __FILE__ ) . 'assets/nika-widget.css' )"));
check('the installed version comes from disk, not the constant in memory',php.includes("$transient->checked[ $plugin_file ] ?? NIKA_VERSION")&&php.includes('version_compare( $installed'));
check('an up to date install is cleared from the update list',php.includes('unset( $transient->response[ $plugin_file ] )')&&php.includes('$transient->no_update[ $plugin_file ]'));
check('menu icon stays bounded with a WordPress-sized label gap',php.includes("wp_add_inline_style(")&&php.includes("width:20px;height:20px")&&php.includes("margin:7px 0 0;")&&php.includes("object-fit:contain"));
check('save confirmation clears the header actions and dismisses itself',adminCss.includes('--wp-admin--admin-bar--height')&&adminCss.includes('.nika-feedback {')&&!adminCss.includes('.nika-feedback { position: fixed; z-index: 100100; top: 46px')&&adminJs.includes('setTimeout')&&adminJs.includes('feedback.remove()'));
check('admin copy avoids decorative AI-style punctuation',!adminPage.includes('—')&&!adminPage.match(/\b0[1-9]\s*[·:]/)&&!adminPage.includes('◈')&&!adminPage.includes('↗'));
check('legacy Settings links redirect to the standalone Nika workspace',php.includes("'options-general.php' !== $pagenow")&&php.includes("admin_url( 'admin.php?page=nika-site-guide' )"));
check('third-party notices cannot break the branded hero',adminCss.includes('.nika-hero__copy > .notice')&&adminCss.includes('#wpbody-content > .pms-cross-promo'));
check('API key stays in server PHP',php.includes("defined( 'NIKA_AI_API_KEY' )")&&php.includes("'Authorization' => 'Bearer ' . $key"));
check('API key is not returned by config',!php.match(/nika_config_response[\s\S]{0,800}api_key/));
check('visitor IP is hashed before storage',php.includes("hash_hmac( 'sha256', $ip")&&php.includes('set_transient( $key'));
check('customer controls visitor and site budgets',php.includes("'hourly_limit'")&&php.includes("'daily_limit'")&&php.includes("'site_daily'"));
check('customer controls features and appearance',php.includes("'navigation'")&&php.includes("'dictation'")&&php.includes("'accent'")&&php.includes("'position'"));
check('customer controls pre-chat starter suggestions',php.includes('nika_sanitize_suggestions')&&php.includes("'suggestions' => $s['suggestions']")&&!php.includes("'greeting' =>"));
check('admin can generate fresh suggestions from published content',php.includes("'/admin/suggestions'")&&php.includes('nika_generate_suggestions_response')&&php.includes('nika_site_index()')&&php.includes("'temperature' => $strict ? 0.4 : 0.9"));
check('suggestion generation requires administrator permission',php.includes("current_user_can( 'manage_options' )"));
check('suggestion generation reports missing keys and provider failures',php.includes('Add an AI API key before generating suggestions.')&&php.includes('Check the API key, model, and provider settings.'));
check('generated suggestions require review before saving',adminJs.includes('Review them, then save changes.')&&adminJs.includes("X-WP-Nonce")&&adminJs.includes("role', type === 'error' ? 'alert' : 'status'"));
check('save confirmation is custom, dismissible and borderless',php.includes("nika-feedback__message")&&!php.includes('settings_errors();')&&adminCss.includes('border: 0')&&adminJs.includes("dismissFeedback.addEventListener"));
check('usage limits include practical examples',adminPage.includes('20 questions before the hourly reset')&&adminPage.includes('15,000 requests in a 30-day month')&&adminPage.includes('roughly 2,000 words')&&adminPage.includes('10 recent question-and-answer exchanges'));
check('customer can exclude content and destinations',php.includes('function nika_excluded_paths')&&php.includes("'excluded_paths'"));
check('excluded paths suppress the widget and reject chat context',php.includes("'nika_excluded'")&&php.includes("if ( in_array( $current_path, nika_excluded_paths(), true ) ) return;"));
check('current-location answers use the live browser snapshot',php.includes('function nika_location_answer')&&php.includes('$direct_location = nika_location_answer'));
check('stale cross-page assistant replies are marked historical',php.includes('Historical reply from another page'));
check('visibility limitations and heading anchors reach the provider',php.includes('Visibility limitations:')&&php.includes('Available heading anchors:'));
check('responses finish cleanly instead of relying on token clipping',php.includes('finish every sentence and point cleanly')&&php.includes("'max_tokens' => 900"));
check('foreign browser origins are rejected',php.includes('function nika_origin_allowed')&&php.includes("'nika_origin'")&&php.includes("'status' => 403"));
check('published WordPress content is locally indexed',php.includes('function nika_site_index()')&&php.includes('$post->post_content'));
check('content index is bounded and cached',php.includes('> 24000')&&php.includes("set_transient( 'nika_site_index_v1'"));
check('new and changed WordPress content invalidates the index',php.includes("add_action( 'save_post'")&&php.includes("add_action( 'deleted_post'"));
check('navigation is server allowlisted',php.includes("in_array( $path, wp_list_pluck( $pages, 'path' ), true )"));
check('cross-origin actions are rejected',php.includes("isset( $parts['host'] )"));
check('REST response hides provider details',php.includes("Nika could not reach the configured AI provider")&&!php.includes('wp_remote_retrieve_body( $response ) ) return new WP_Error'));
check('widget is loaded from the plugin, not Abatchan',php.includes("plugin_dir_url( __FILE__ ) . 'assets/nika-widget.js'")&&!php.includes("NIKA_SITE_GUIDE_SERVICE"));
check('packaged widget matches shared core',widget===canonical);
check('external AI services are disclosed',readme.includes('== Third-party services ==')&&readme.includes('OpenAI:')&&readme.includes('DeepSeek:'));
check('readme promises no form submission',readme.includes('does not submit forms'));
check('readme distinguishes controls from safeguards',readme.includes('Which limits can I control?')&&readme.includes('cannot be disabled'));

if(failed)process.exit(1);
console.log('\nall passed');
